### ISSUE TITLE
[Bug][move compiler] panick: 'unexpected specification construct' at translate.rs:980:24

### ISSUE THREAD

**Issue by rvantonder** [diem/diem#7385]
# 🐛 Bug

This program causes a panick in `move-build`:

```rust
module M {
    resource struct R {}

    fun t() {
        R = ();
    }
}
```

with

```
thread 'main' panicked at 'unexpected specification construct', language/move-lang/src/naming/translate.rs:980:24
```

## To reproduce

Shell command:

```bash
cat <<EOF > /tmp/crash.move && move-build /tmp/crash.move
module M {
    resource struct R {}

    fun t() {
        R = ();
    }
}
EOF
```

**Stack trace/error message**

<details>
<summary><b>click to expand trace</b></summary>

```
stack backtrace:                                                                                                                                                                                           [71/1859]
   0: std::panicking::begin_panic
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:505
   1: move_lang::naming::translate::lvalue
             at /usr0/home/rijnard/diem-MASTER-confirm/language/move-lang/src/naming/translate.rs:980
   2: move_lang::naming::translate::lvalue_list::{{closure}}
             at /usr0/home/rijnard/diem-MASTER-confirm/language/move-lang/src/naming/translate.rs:1001
   3: core::iter::adapters::map_try_fold::{{closure}}
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/iter/adapters/mod.rs:912
   4: core::iter::traits::iterator::Iterator::try_fold
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/iter/traits/iterator.rs:1888
   5: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/iter/adapters/mod.rs:938
   6: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/iter/adapters/mod.rs:938
   7: <core::iter::adapters::ResultShunt<I,E> as core::iter::traits::iterator::Iterator>::try_fold
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/iter/adapters/mod.rs:2949
   8: core::iter::traits::iterator::Iterator::find
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/iter/traits/iterator.rs:2231
   9: <core::iter::adapters::ResultShunt<I,E> as core::iter::traits::iterator::Iterator>::next
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/iter/adapters/mod.rs:2931
  10: <alloc::vec::Vec<T> as alloc::vec::SpecFromIterNested<T,I>>::from_iter
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/alloc/src/vec.rs:2125
  11: <alloc::vec::Vec<T> as alloc::vec::SpecFromIter<T,I>>::from_iter
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/alloc/src/vec.rs:2162
  12: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/alloc/src/vec.rs:2002
  13: core::iter::traits::iterator::Iterator::collect
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/iter/traits/iterator.rs:1670
  14: <core::result::Result<V,E> as core::iter::traits::collect::FromIterator<core::result::Result<A,E>>>::from_iter::{{closure}}
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/result.rs:1490
  15: core::iter::adapters::process_results
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/iter/adapters/mod.rs:2920
  16: <core::result::Result<V,E> as core::iter::traits::collect::FromIterator<core::result::Result<A,E>>>::from_iter
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/result.rs:1490
  17: core::iter::traits::iterator::Iterator::collect
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/iter/traits/iterator.rs:1670
  18: <core::option::Option<V> as core::iter::traits::collect::FromIterator<core::option::Option<A>>>::from_iter
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/option.rs:1626
  19: core::iter::traits::iterator::Iterator::collect
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/iter/traits/iterator.rs:1670
  20: move_lang::naming::translate::lvalue_list
             at /usr0/home/rijnard/diem-MASTER-confirm/language/move-lang/src/naming/translate.rs:1000
  21: move_lang::naming::translate::assign_list
             at /usr0/home/rijnard/diem-MASTER-confirm/language/move-lang/src/naming/translate.rs:990
  22: move_lang::naming::translate::exp_
             at /usr0/home/rijnard/diem-MASTER-confirm/language/move-lang/src/naming/translate.rs:792
  23: move_lang::naming::translate::sequence_item
             at /usr0/home/rijnard/diem-MASTER-confirm/language/move-lang/src/naming/translate.rs:726
  24: move_lang::naming::translate::sequence::{{closure}}
             at /usr0/home/rijnard/diem-MASTER-confirm/language/move-lang/src/naming/translate.rs:718
  25: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/ops/function.rs:280
  26: core::option::Option<T>::map
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/option.rs:450
  27: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::next
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/iter/adapters/mod.rs:924
  28: <alloc::collections::vec_deque::VecDeque<A> as core::iter::traits::collect::Extend<A>>::extend
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/alloc/src/collections/vec_deque.rs:2978
  29: <alloc::collections::vec_deque::VecDeque<A> as core::iter::traits::collect::FromIterator<A>>::from_iter
  ...
```

</details>

## Expected Behavior

No panick/crash, probably want to raise a friendlier compile error message?

## System information

**Please complete the following information:**
- Diem Version: master @ ed132a8516aa5ff84298efcf1f119971509ea8d4
- rustc 1.48.0 (7eac88abb 2020-11-16)
- Ubuntu 18.04.5 LTS

## Additional context

Found as part of a compiler fuzzing project that mutates programs: https://github.com/agroce/afl-compiler-fuzzer and https://github.com/comby-tools/comby-mutation-server.

**Comment by tnowacki** [comment]
I think I marked the wrong issue in #7401
