### ISSUE TITLE
[Bug][move compiler] Panick: 'called `Result::unwrap()` on an `Err` value: ParseIntError { kind: Overflow }' at syntax.rs:485:39

### ISSUE THREAD

**Issue by rvantonder** [diem/diem#7388]
# 🐛 Bug

This program causes a panick in `move-build`:

```rust
script {
fun main() {
    assert(1u128 + 340282366920938463463374607431768211454u128 == 340282366920938463463374607431768211455u128, 1201);
}
}

script {
fun main() {
    assert(340282366920938463463374607431768211454u128 % 340282366920938463463374617431768211455u128 == 340282366920938463463374607431768211454u128, 5200);
}
}
```

with

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ParseIntError { kind: Overflow }', language/move-lang/src/parser/syntax.rs:485:39
```

## To reproduce

Shell command:

```bash
cat <<EOF > /tmp/crash.move && move-build /tmp/crash.move
script {
fun main() {
    assert(1u128 + 340282366920938463463374607431768211454u128 == 340282366920938463463374607431768211455u128, 1201);
}
}

script {
fun main() {
    assert(340282366920938463463374607431768211454u128 % 340282366920938463463374617431768211455u128 == 340282366920938463463374607431768211454u128, 5200);
}
}
EOF
```

**Stack trace/error message**

<details>
<summary><b>click to expand trace</b></summary>

```
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:483
   1: core::panicking::panic_fmt
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/panicking.rs:85
   2: core::option::expect_none_failed
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/option.rs:1234
   3: core::result::Result<T,E>::unwrap
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/result.rs:973
   4: move_lang::parser::syntax::parse_value
             at /usr0/home/rijnard/diem-MASTER-confirm/language/move-lang/src/parser/syntax.rs:485
   5: move_lang::parser::syntax::parse_term
             at /usr0/home/rijnard/diem-MASTER-confirm/language/move-lang/src/parser/syntax.rs:628
   6: move_lang::parser::syntax::parse_dot_or_index_chain
             at /usr0/home/rijnard/diem-MASTER-confirm/language/move-lang/src/parser/syntax.rs:1013
   7: move_lang::parser::syntax::parse_unary_exp
             at /usr0/home/rijnard/diem-MASTER-confirm/language/move-lang/src/parser/syntax.rs:999
   8: move_lang::parser::syntax::parse_binop_exp
             at /usr0/home/rijnard/diem-MASTER-confirm/language/move-lang/src/parser/syntax.rs:911
   9: move_lang::parser::syntax::parse_exp
             at /usr0/home/rijnard/diem-MASTER-confirm/language/move-lang/src/parser/syntax.rs:833
  10: core::ops::function::Fn::call
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/ops/function.rs:70
  11: move_lang::parser::syntax::parse_comma_list_after_start
             at /usr0/home/rijnard/diem-MASTER-confirm/language/move-lang/src/parser/syntax.rs:168
  12: move_lang::parser::syntax::parse_comma_list
             at /usr0/home/rijnard/diem-MASTER-confirm/language/move-lang/src/parser/syntax.rs:134
  13: move_lang::parser::syntax::parse_call_args
             at /usr0/home/rijnard/diem-MASTER-confirm/language/move-lang/src/parser/syntax.rs:744
  14: move_lang::parser::syntax::parse_name_exp
             at /usr0/home/rijnard/diem-MASTER-confirm/language/move-lang/src/parser/syntax.rs:732
  15: move_lang::parser::syntax::parse_term
             at /usr0/home/rijnard/diem-MASTER-confirm/language/move-lang/src/parser/syntax.rs:612
  16: move_lang::parser::syntax::parse_dot_or_index_chain
             at /usr0/home/rijnard/diem-MASTER-confirm/language/move-lang/src/parser/syntax.rs:1013
  17: move_lang::parser::syntax::parse_unary_exp
             at /usr0/home/rijnard/diem-MASTER-confirm/language/move-lang/src/parser/syntax.rs:999
  18: move_lang::parser::syntax::parse_exp
             at /usr0/home/rijnard/diem-MASTER-confirm/language/move-lang/src/parser/syntax.rs:831
  19: move_lang::parser::syntax::parse_sequence_item
             at /usr0/home/rijnard/diem-MASTER-confirm/language/move-lang/src/parser/syntax.rs:539
  20: move_lang::parser::syntax::parse_sequence
             at /usr0/home/rijnard/diem-MASTER-confirm/language/move-lang/src/parser/syntax.rs:561
  21: move_lang::parser::syntax::parse_function_decl
             at /usr0/home/rijnard/diem-MASTER-confirm/language/move-lang/src/parser/syntax.rs:1373
  22: move_lang::parser::syntax::parse_script
             at /usr0/home/rijnard/diem-MASTER-confirm/language/move-lang/src/parser/syntax.rs:1663
  23: move_lang::parser::syntax::parse_file
             at /usr0/home/rijnard/diem-MASTER-confirm/language/move-lang/src/parser/syntax.rs:2280
  24: move_lang::parser::syntax::parse_file_string
             at /usr0/home/rijnard/diem-MASTER-confirm/language/move-lang/src/parser/syntax.rs:2303
  25: move_lang::parse_file
             at /usr0/home/rijnard/diem-MASTER-confirm/language/move-lang/src/lib.rs:700
  26: move_lang::parse_program
             at /usr0/home/rijnard/diem-MASTER-confirm/language/move-lang/src/lib.rs:574
  27: move_lang::move_parse
             at /usr0/home/rijnard/diem-MASTER-confirm/language/move-lang/src/lib.rs:209
  28: move_lang::move_compile
             at /usr0/home/rijnard/diem-MASTER-confirm/language/move-lang/src/lib.rs:156
  ...
```

</details>

## Expected Behavior

No panick/crash, probably want to raise a friendlier compile error message?

## System information

**Please complete the following information:**
- Diem Version: master @ ed132a8516aa5ff84298efcf1f119971509ea8d4
- rustc 1.48.0 (7eac88abb 2020-11-16)
- Ubuntu 18.04.5 LTS

## Additional context

Found as part of a compiler fuzzing project that mutates programs: https://github.com/agroce/afl-compiler-fuzzer and https://github.com/comby-tools/comby-mutation-server.

**Comment by bob-wilson** [comment]
Looks like a parser bug. We're not checking if constants are within range. I can take this one but CC'ing Todd for visibility

**Comment by bob-wilson** [comment]
I tried putting in the obvious fix in the parser but then was reminded that the parser's error handling needs some work so that it doesn't completely bail out at the first error. Alternatively we could do the integer literal size check in the expansion phase, but this might be a good time to think about the general problem in the parser.
