### ISSUE TITLE
[Bug][move compiler] Panick: context.has_errors() called at translate.rs:652:9

### ISSUE THREAD

**Issue by rvantonder** [diem/diem#7561]
# 🐛 Bug

This program causes a panick in `move-build`:

```rust
script {
    const A: bool = true;
    const A: bool = true;
    fun main() {}
}
```

with

```
thread 'main' panicked at 'assertion failed: context.has_errors()', language/move-lang/src/expansion/translate.rs:652:9
```

## To reproduce

Shell command:

```bash
cat <<EOF > /tmp/crash.move && move-build /tmp/crash.move
script {
    const CAST2: u128 = ();
    const CAST2: u128 = ();
    fun main() {}
}
EOF
```

**Stack trace/error message**

<details>
<summary><b>click to expand trace</b></summary>

```
stack backtrace:
   0: std::panicking::begin_panic
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:505
   1: move_lang::expansion::translate::constant
             at /usr0/home/rijnard/diem-MASTER-confirm/language/move-lang/src/expansion/translate.rs:652
```

</details>

## Expected Behavior

No panick/crash, probably want to raise a friendlier compile error message?

## System information

**Please complete the following information:**
- Diem Version: master @ 4130cb0e068d01faa769ec09961fe2b97e6b43c1
- rustc 1.48.0 (7eac88abb 2020-11-16)
- Ubuntu 18.04.5 LTS

## Additional context

Found as part of a compiler fuzzing project that mutates programs: https://github.com/agroce/afl-compiler-fuzzer and https://github.com/comby-tools/comby-mutation-server.

**Comment by tnowacki** [comment]
Might be a while for this one. Not a lot of point in fixing this without getting in a real fix, which is allowing `Self` inside of script blocks. This would in turn allow this duplicate const name issue to be solved by the alias check already in place
