### ISSUE TITLE
[Bug][Move compiler] Panic:  'ICE invalid use of tmp local' at state.rs:315

### ISSUE THREAD

**Issue by rvantonder** [diem/diem#7571]
# 🐛 Bug

This program causes a panick in `move-build`:

```rust
script {
fun main() {
    let x = 5;
    let x_ref;
    let y_ref;
    x_ref = &x;
    y_ref = x_ref;
    while(true)
        x_ref = &8;
    assert(*x_ref < 2, 42);
    y_ref;
}
}
```

with

```
thread 'main' panicked at 'ICE invalid use of tmp local tmp%#17', language/move-lang/src/cfgir/borrows/state.rs:315:36
```

Side note: this is a pretty minimal test case, every line in the above program is required for the crash.

## To reproduce

Shell command:

```bash
cat <<EOF > /tmp/crash.move && move-build /tmp/crash.move
script {
fun main() {
    let x = 5;
    let x_ref;
    let y_ref;
    x_ref = &x;
    y_ref = x_ref;
    while(true)
        x_ref = &8;
    assert(*x_ref < 2, 42);
    y_ref;
}
}
EOF
```

**Stack trace/error message**

<details>
<summary><b>click to expand trace</b></summary>

```
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:483
   1: std::panicking::begin_panic_fmt
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:437
   2: move_lang::cfgir::borrows::state::BorrowState::check_use_borrowed_by::{{closure}}
             at /usr0/home/rijnard/diem-MASTER-confirm/language/move-lang/src/cfgir/borrows/state.rs:315
```

</details>

## Expected Behavior

No panick/crash, probably want to raise a friendlier compile error message?

## System information

**Please complete the following information:**
- Diem Version: master @ 4130cb0e068d01faa769ec09961fe2b97e6b43c1
- rustc 1.48.0 (7eac88abb 2020-11-16)
- Ubuntu 18.04.5 LTS

## Additional context

Found as part of a compiler fuzzing project that mutates programs: https://github.com/agroce/afl-compiler-fuzzer and https://github.com/comby-tools/comby-mutation-server.

**Comment by tnowacki** [comment]
This one is a bit of a doozy. Really I don't think we should error in this case (the assertion fails for trying to generate a message in this case). But it is unclear if it is easy to completely fix it by a deeper change in the borrow graph

**Comment by tnowacki** [comment]
cc @shazqadeer @sblackshear
