### ISSUE TITLE
[Bug] VMError:: into_vm_status may panic when converting errors with code OUT_OF_GAS

### ISSUE THREAD

**Issue by vgao1996** [diem/diem#7614]
This function will panic if it receives an OUT_OF_GAS error without an index. The exact condition under which this is triggered is yet to be figured out.

To reproduce, run this functional test:
```
//! account: Alice, 0

// this sets up Alice's account with very low balance, which is not sufficient to cover the gas cost

//! sender: Alice
//! max-gas: 5
main() {
    let x: u64;
    let y: u64;

    x = 3;
    y = 5;

    assert(move(x) + move(y) == 8, 42);
    return;
}

// check: MAX_GAS_UNITS_BELOW_MIN_TRANSACTION_GAS_UNITS
```
and the program will panic
```
thread 'run_test::a.mvir' panicked at 'Unexpected offsets. major_status: OUT_OF_GASsub_status: Nonelocation: Undefinedoffsets: []', language/vm/src/errors.rs:69:17
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:483
   1: std::panicking::begin_panic_fmt
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:437
   2: vm::errors::VMError::into_vm_status
             at /Users/vgao/libra/language/vm/src/errors.rs:69
   3: diem_vm::diem_vm::charge_global_write_gas_usage::{{closure}}
             at /Users/vgao/libra/language/diem-vm/src/diem_vm.rs:540
   4: core::result::Result<T,E>::map_err
             at /Users/vgao/.rustup/toolchains/1.48.0-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/result.rs:595
   5: diem_vm::diem_vm::charge_global_write_gas_usage
             at /Users/vgao/libra/language/diem-vm/src/diem_vm.rs:538
   6: diem_vm::diem_transaction_executor::DiemVM::execute_script
             at /Users/vgao/libra/language/diem-vm/src/diem_transaction_executor.rs:187
   7: diem_vm::diem_transaction_executor::DiemVM::execute_user_transaction
             at /Users/vgao/libra/language/diem-vm/src/diem_transaction_executor.rs:284
   8: diem_vm::diem_transaction_executor::DiemVM::execute_block_impl
             at /Users/vgao/libra/language/diem-vm/src/diem_transaction_executor.rs:656
   9: diem_vm::diem_transaction_executor::DiemVM::execute_block_and_keep_vm_status
             at /Users/vgao/libra/language/diem-vm/src/diem_transaction_executor.rs:721
  10: language_e2e_tests::executor::FakeExecutor::execute_block_and_keep_vm_status
             at /Users/vgao/libra/language/testing-infra/e2e-tests/src/executor.rs:226
  11: functional_tests::evaluator::run_transaction
             at /Users/vgao/libra/language/testing-infra/functional-tests/src/evaluator.rs:419
  12: functional_tests::evaluator::eval_transaction
             at /Users/vgao/libra/language/testing-infra/functional-tests/src/evaluator.rs:626
  13: functional_tests::evaluator::eval
             at /Users/vgao/libra/language/testing-infra/functional-tests/src/evaluator.rs:752
  14: functional_tests::testsuite::functional_tests
             at /Users/vgao/libra/language/testing-infra/functional-tests/src/testsuite.rs:326
  15: testsuite::run_test
             at ./tests/testsuite.rs:64
  16: datatest_stable::runner::Requirements::expand::{{closure}}::{{closure}}
             at /Users/vgao/libra/common/datatest-stable/src/runner.rs:323
  17: <alloc::boxed::Box<F> as core::ops::function::Fn<A>>::call
             at /Users/vgao/.rustup/toolchains/1.48.0-x86_64-apple-darwin/lib/rustlib/src/rust/library/alloc/src/boxed.rs:1056
  18: datatest_stable::runner::run_test::{{closure}}::{{closure}}
             at /Users/vgao/libra/common/datatest-stable/src/runner.rs:172
  19: core::ops::function::FnOnce::call_once
             at /Users/vgao/.rustup/toolchains/1.48.0-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:227
  20: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /Users/vgao/.rustup/toolchains/1.48.0-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/panic.rs:308
  21: std::panicking::try::do_call
             at /Users/vgao/.rustup/toolchains/1.48.0-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/panicking.rs:381
  22: ___rust_try
  23: std::panicking::try
             at /Users/vgao/.rustup/toolchains/1.48.0-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/panicking.rs:345
  24: std::panic::catch_unwind
             at /Users/vgao/.rustup/toolchains/1.48.0-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/panic.rs:382
  25: datatest_stable::runner::run_test::{{closure}}
             at /Users/vgao/libra/common/datatest-stable/src/runner.rs:172
```

**Comment by bob-wilson** [comment]
The problem here is that there is enough gas to execute the script but not enough to pay for updating the global state in the diem-vm code. The `VMError::into_vm_status` function has a `debug_assert` that complains about a `StatusType::Execution` error where the "offsets" vector is empty, but ignoring the assertion (e.g., in a release build), the code does the right thing in that case: it reports `VMStatus::Error(OUT_OF_GAS)` instead of `VMStatus::ExecutionFailure(OUT_OF_GAS)`.  The `ExecutionFailure` status is supposed to be used for errors that occur while executing Move code, which is not the case here, so an `Error` status seems correct. We check for `OUT_OF_GAS`  with both of those, so I think this is all fine.

I checked the history of that `debug_assert`: @tnowacki added it last July in #5071. It appears that at the time, this was used to help track down some "todo" cases. Some related assertions were later removed in #5778 but this one was kept, along with a "TODO" comment in the code. Since we're not seeing this assertion fail in any other cases, it seems like we've already fixed the cases where the offsets information was missing. I think we can just remove the `debug_assert` now, and I'm testing a PR to do that.

**Comment by tnowacki** [comment]
This is definitely an oddity and I'm not sure the debug assert should be removed. (It did its job)

I haven't looked into this one too closely yet, but the error system correctly assumes that each status code can only be used in one bucket. If we want OUT_OF_GAS to straddle two, I would suggest either adding another status code or special casing it in the debug asserts

**Comment by bob-wilson** [comment]
The `keep_or_discard` function in move-core/types/src/vm_status.rs has a special case for `OUT_OF_GAS` to allow it for either `ExecutionFailure` or `Error` statuses, so I thought this was intentional.  See #6133 where that was added. I would be fine with a special case in the `debug_assert`.
