### ISSUE TITLE
[mempool] Flaky multi-node failover test

### ISSUE THREAD

**Issue by phlip9** [diem/diem#8423]
Caught this in CI on an unrelated change:

```
--- TRY 3 STDOUT:                                             diem-mempool  tests::multi_node_test::test_failover ---

running 1 test
test tests::multi_node_test::test_failover ... FAILED

failures:

failures:
    tests::multi_node_test::test_failover

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 34 filtered out; finished in 0.14s

--- TRY 3 STDERR:                                             diem-mempool  tests::multi_node_test::test_failover ---
thread 'tests::multi_node_test::test_failover' panicked at 'Failed to get expected event 'PeerStateChange'', mempool/src/tests/node.rs:431:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:493:5
   1: std::panicking::begin_panic_fmt
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:435:5
   2: diem_mempool::tests::node::Node::wait_for_event
             at ./src/tests/node.rs:431:9
   3: diem_mempool::tests::node::Node::send_connection_event
             at ./src/tests/node.rs:421:9
   4: diem_mempool::tests::node::Node::send_lost_peer_event
             at ./src/tests/node.rs:415:9
   5: diem_mempool::tests::multi_node_test::TestHarness::disconnect
             at ./src/tests/multi_node_test.rs:276:9
   6: diem_mempool::tests::multi_node_test::test_failover
             at ./src/tests/multi_node_test.rs:744:5
   7: diem_mempool::tests::multi_node_test::test_failover::{{closure}}
             at ./src/tests/multi_node_test.rs:716:1
   8: core::ops::function::FnOnce::call_once
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/ops/function.rs:227:5
   9: core::ops::function::FnOnce::call_once
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Looks like a race condition : )

**Comment by gregnazario** [comment]
It is a race condition, which would require probably looping in a controlled clock to determine ordering.

It's pretty hard to fix any of the tests involved with it, but it's little low priority
