### ISSUE TITLE
[Bug] socket bench failed

### ISSUE THREAD

**Issue by Srtake** [diem/diem#8487]
# 🐛 Bug

I tried to run the memsocket + noise benchmark, but got an error:
`thread 'thread 'tokio-runtime-worker' panicked at 'internal error: entered unreachable code', /home/kz/fork/diem/network/src/noise/handshake.rs:178:69`

## To reproduce

**Code snippet to reproduce**
I just followed the steps in the comment:
```rust
TCP_NOISE_ADDR=/ip6/::1/tcp/12345 cargo run --release -p socket-bench-server
TCP_NOISE_ADDR=/ip6/::1/tcp/12345 cargo x bench -p network noise_connections
```

**Stack trace/error message**
Client:
```
thread 'thread 'tokio-runtime-worker' panicked at 'internal error: entered unreachable code', /home/kz/fork/diem/network/src/noise/handshake.rs:178:69
```

Server:
```
2021-06-06T02:30:11.358480Z [tokio-runtime-worker] ERROR network/socket-bench-server/src/lib.rs:151 Connection upgrade failed Custom { kind: Other, error: ServerReadFailed(Kind(UnexpectedEof)) } {"error":"Custom { kind: Other, error: ServerReadFailed(Kind(UnexpectedEof)) }"}
```

## Expected Behavior
The benchmark runs successfully, and output the result as the comments saying:
```
/// connection_throughput/noise_connections/128
///                         time:   [69.816 ms 70.666 ms 71.679 ms]
///                         thrpt:  [1.7857 Kelem/s 1.8113 Kelem/s 1.8334 Kelem/s]
///                  change:
///                         time:   [-9.0403% -4.6666% -0.6491%] (p = 0.06 > 0.05)
///                         thrpt:  [+0.6533% +4.8951% +9.9388%]
```

## System information
- Diem version: Current main branch
- Rust version: cargo 1.51.0
- OS: Ubuntu 16.04

**Comment by Srtake** [comment]
I ran `cargo bench -p network` and also met this problem when the bench start running memsocket + noise (and tcp + noise). According to the error message, the remote public key input into `upgrade_with_noise` is None, which is extracted from `addr` in the closure in `build_memsocket_noise_transport` (and in tcp+noise, it's `build_tcp_noise_transport`). I tried to print the addr in the closure, but found nothing that can be extracted to a `x25519` public key.

**Comment by phlip9** [comment]
Thanks for the report! Unfortunately, we've gone through a few refactors of both the transport code and the NetworkAddress data type; I don't believe we've maintained the socket bench during that time (just barely kept it compiling), but this is definitely something we should clean up at some point. As far as the problem you're experiencing, we've since moved to a Noise IK handshake, which means the client needs to know the server pubkey before it connects. The bench transports need to be refactored so they don't just sample a new keypair for every connection and we need some way to get the server pubkey to the bench client (print and copy?).

Ideally we add a small \#[test] which exercises the socket bench so it doesn't break in the future.

**Comment by gregnazario** [comment]
Yeah, it's been a long time since we've given this code path some love.

I think our future plan in general is probably to replace this bench with a new one altogether that matches more with the current state of the networking.

**Comment by Srtake** [comment]
Thanks for response! I have skimmed the code of bench server before, and found that there is no public key sharing, which is the assumption of Noise IK. So the problem is that there is no keypair generation in the bench transports, and we need to add the process in bench transports construction and print the public key in cmd (or add it in the network address?) to share the key with potential clients. Am I right?

**Comment by phlip9** [comment]
Right, I wrote these benchmarks back when we used Noise IX (which exchanges pubkeys in-band). The problem here is that the client transport needs to know the server's noise pubkey when it dials. The other problem is that the current Transport trait needs overhauling so it can better compose and push the NetworkAddress through to sub-transports. To give some context, here's a past discussion about "eventually" refactoring Transport, which uhh... clearly didn't happen : p

https://github.com/diem/diem/pull/3478#issuecomment-617385633

**Comment by Srtake** [comment]
So I have a question: why should the server's pubkey be placed in Transport trait (and then peel off from its NetworkAddress)? The Transport trait takes the responsibility for constructing low layer connection (like memory sockets and tcp connections), which i think is not relative with static public key (which is used in higher layer Noise IK connection). The additional public key is redundant for connections with no Noise encryption (like benchmarks with no `+noise` marks). So I think the solution with minimal workload is just modify socket bench server implementation and let the server generate and store its keypair for itself.

**Comment by phlip9** [comment]
After looking at the socket bench a little closer, we would probably want to pass in our key pair to the `build_<x>_noise_transport` builders instead of generating a random one each time. We would also need the server to print out its full network address with noise pubkey included. That's probably the minimal approach to get this working w/o too much trouble : )

**Comment by Srtake** [comment]
I agree. If nothing goes wrong, I think the key pair will be generated in `socket_bench` method and input into `build_<x>_noise_transport` builders, then `start_stream_server` method which returns full addr of the server.

**Comment by Srtake** [comment]
I tried to rewrite `socket_bench()` to generate keypairs in the function, and pass them in `build_<x>_noise_transport` functions. But several of them are in closures with move keyword, so the private key value will be moved in these closures due to lack of `Copy` implementation of `x25519::PrivateKey`. To solve the problem, I have to generate different local keypairs for memsocket, tcpsocket and remote connection, which leads to a bunch of key generation code in `socket_bench` function. Finally the code works successfully, but I want to know whether there is a better solution to this problem.
