### ISSUE TITLE
[Bug][move-model] crash in ty.rs

### ISSUE THREAD

**Issue by sblackshear** [diem/diem#9155]
# 🐛 Bug

Crash inside move-model/ty.rs while attempting to run prover on some StarCoin code for benchmarking

## To reproduce

**Code snippet to reproduce**
See attached repro.
[repro.zip](https://github.com/diem/diem/files/7156308/repro.zip)

```rust
unzip repro.zip
mvp crash_repro/starswap_modules crash_repro/starcoin_modules
```

**Stack trace/error message**
```
thread 'main' panicked at 'index out of bounds: the len is 1 but the index is 1', language/move-model/src/ty.rs:270:21
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:515:5
   1: core::panicking::panic_fmt
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/panicking.rs:92:14
   2: core::panicking::panic_bounds_check
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/panicking.rs:69:5
   3: move_model::ty::Type::replace
             at ./language/move-model/src/ty.rs:270:21
   4: move_model::ty::Type::replace::{{closure}}::{{closure}}
             at ./language/move-model/src/ty.rs:266:65
   5: core::iter::adapters::map::map_fold::{{closure}}
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/iter/adapters/map.rs:82:28
   6: core::iter::traits::iterator::Iterator::fold
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/iter/traits/iterator.rs:2112:21
   7: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/iter/adapters/map.rs:122:9
   8: core::iter::traits::iterator::Iterator::for_each
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/iter/traits/iterator.rs:736:9
   9: <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/alloc/src/vec/spec_extend.rs:40:17
  10: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/alloc/src/vec/spec_from_iter_nested.rs:56:9
  11: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/alloc/src/vec/spec_from_iter.rs:33:9
  12: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/alloc/src/vec/mod.rs:2449:9
  13: core::iter::traits::iterator::Iterator::collect
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/iter/traits/iterator.rs:1748:9
  14: move_model::ty::Type::replace::{{closure}}
             at ./language/move-model/src/ty.rs:266:44
  15: move_model::ty::Type::replace
             at ./language/move-model/src/ty.rs:293:70
  16: move_model::ty::Type::replace::{{closure}}::{{closure}}
             at ./language/move-model/src/ty.rs:266:65
  17: core::iter::adapters::map::map_fold::{{closure}}
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/iter/adapters/map.rs:82:28
  18: core::iter::traits::iterator::Iterator::fold
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/iter/traits/iterator.rs:2112:21
  19: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/iter/adapters/map.rs:122:9
  20: core::iter::traits::iterator::Iterator::for_each
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/iter/traits/iterator.rs:736:9
  21: <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/alloc/src/vec/spec_extend.rs:40:17
  22: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/alloc/src/vec/spec_from_iter_nested.rs:56:9
  23: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/alloc/src/vec/spec_from_iter.rs:33:9
  24: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/alloc/src/vec/mod.rs:2449:9
  25: core::iter::traits::iterator::Iterator::collect
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/iter/traits/iterator.rs:1748:9
  26: move_model::ty::Type::replace::{{closure}}
             at ./language/move-model/src/ty.rs:266:44
  27: move_model::ty::Type::replace
             at ./language/move-model/src/ty.rs:293:70
  28: move_model::ty::Type::instantiate
             at ./language/move-model/src/ty.rs:233:13
  29: <move_model::spec_translator::SpecTranslator<T> as move_model::exp_rewriter::ExpRewriterFunctions>::rewrite_temporary
             at ./language/move-model/src/spec_translator.rs:628:34
  30: move_model::exp_rewriter::ExpRewriterFunctions::rewrite_exp_descent
             at ./language/move-model/src/exp_rewriter.rs:185:40
  31: <move_model::spec_translator::SpecTranslator<T> as move_model::exp_rewriter::ExpRewriterFunctions>::rewrite_exp
             at ./language/move-model/src/spec_translator.rs:582:19
  32: move_model::exp_rewriter::ExpRewriterFunctions::internal_rewrite_exp
             at ./language/move-model/src/exp_rewriter.rs:342:23
  33: move_model::exp_rewriter::ExpRewriterFunctions::internal_rewrite_vec
             at ./language/move-model/src/exp_rewriter.rs:352:30
  34: move_model::exp_rewriter::ExpRewriterFunctions::rewrite_exp_descent
             at ./language/move-model/src/exp_rewriter.rs:205:36
  35: <move_model::spec_translator::SpecTranslator<T> as move_model::exp_rewriter::ExpRewriterFunctions>::rewrite_exp
             at ./language/move-model/src/spec_translator.rs:582:19
  36: move_model::exp_rewriter::ExpRewriterFunctions::internal_rewrite_exp
             at ./language/move-model/src/exp_rewriter.rs:342:23
  37: move_model::exp_rewriter::ExpRewriterFunctions::internal_rewrite_vec
             at ./language/move-model/src/exp_rewriter.rs:361:32
  38: move_model::exp_rewriter::ExpRewriterFunctions::rewrite_exp_descent
             at ./language/move-model/src/exp_rewriter.rs:205:36
  39: <move_model::spec_translator::SpecTranslator<T> as move_model::exp_rewriter::ExpRewriterFunctions>::rewrite_exp
             at ./language/move-model/src/spec_translator.rs:582:19
  40: move_model::exp_rewriter::ExpRewriterFunctions::internal_rewrite_exp
             at ./language/move-model/src/exp_rewriter.rs:342:23
  41: move_model::exp_rewriter::ExpRewriterFunctions::internal_rewrite_vec
             at ./language/move-model/src/exp_rewriter.rs:360:32
  42: move_model::exp_rewriter::ExpRewriterFunctions::rewrite_exp_descent
             at ./language/move-model/src/exp_rewriter.rs:205:36
  43: <move_model::spec_translator::SpecTranslator<T> as move_model::exp_rewriter::ExpRewriterFunctions>::rewrite_exp
             at ./language/move-model/src/spec_translator.rs:582:19
  44: move_model::spec_translator::SpecTranslator<T>::translate_exp
             at ./language/move-model/src/spec_translator.rs:473:9
  45: move_model::spec_translator::SpecTranslator<T>::translate_spec
             at ./language/move-model/src/spec_translator.rs:355:17
  46: move_model::spec_translator::SpecTranslator<T>::translate_fun_spec
             at ./language/move-model/src/spec_translator.rs:225:9
  47: bytecode::spec_instrumentation::Instrumenter::instrument_call
             at ./language/move-prover/bytecode/src/spec_instrumentation.rs:496:31
  48: bytecode::spec_instrumentation::Instrumenter::instrument_bytecode
             at ./language/move-prover/bytecode/src/spec_instrumentation.rs:455:17
  49: bytecode::spec_instrumentation::Instrumenter::instrument
             at ./language/move-prover/bytecode/src/spec_instrumentation.rs:380:13
  50: bytecode::spec_instrumentation::Instrumenter::run
             at ./language/move-prover/bytecode/src/spec_instrumentation.rs:265:9
  51: <bytecode::spec_instrumentation::SpecInstrumentationProcessor as bytecode::function_target_pipeline::FunctionTargetProcessor>::process
             at ./language/move-prover/bytecode/src/spec_instrumentation.rs:120:33
  52: bytecode::function_target_pipeline::FunctionTargetProcessor::process_and_maybe_remove
             at ./language/move-prover/bytecode/src/function_target_pipeline.rs:96:14
  53: bytecode::function_target_pipeline::FunctionTargetsHolder::process
             at ./language/move-prover/bytecode/src/function_target_pipeline.rs:263:43
  54: bytecode::function_target_pipeline::FunctionTargetPipeline::run_with_hook
             at ./language/move-prover/bytecode/src/function_target_pipeline.rs:370:21
  55: bytecode::function_target_pipeline::FunctionTargetPipeline::run
             at ./language/move-prover/bytecode/src/function_target_pipeline.rs:380:9
  56: move_prover::create_and_process_bytecode
             at ./language/move-prover/src/lib.rs:239:9
  57: move_prover::run_move_prover_with_model
             at ./language/move-prover/src/lib.rs:114:19
  58: move_prover::run_move_prover
             at ./language/move-prover/src/lib.rs:58:5
  59: move_prover::run
             at ./language/move-prover/src/main.rs:33:5
  60: move_prover::main
             at ./language/move-prover/src/main.rs:12:21
  61: core::ops::function::FnOnce::call_once
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/ops/function.rs:227:5
```

## System information

Using latest Diem, version d2a6c5c0017cc5edcec82046b8a1baae41378393

**Comment by mengxu-fb** [comment]
I'll take this, seems to be related to the spec instrumentation pass.

**Comment by sblackshear** [comment]
The issue is indeed fixed for this example, but I'm seeing a crash in the same location on a different one:

[crash_repro.zip](https://github.com/diem/diem/files/7171951/crash_repro.zip)

```
thread 'main' panicked at 'index out of bounds: the len is 1 but the index is 1', language/move-model/src/ty.rs:270:21
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:515:5
   1: core::panicking::panic_fmt
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/panicking.rs:92:14
   2: core::panicking::panic_bounds_check
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/panicking.rs:69:5
   3: move_model::ty::Type::replace
             at ./language/move-model/src/ty.rs:270:21
   4: move_model::ty::Type::replace::{{closure}}::{{closure}}
             at ./language/move-model/src/ty.rs:266:65
   5: core::iter::adapters::map::map_fold::{{closure}}
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/iter/adapters/map.rs:82:28
   6: core::iter::traits::iterator::Iterator::fold
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/iter/traits/iterator.rs:2112:21
   7: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/iter/adapters/map.rs:122:9
   8: core::iter::traits::iterator::Iterator::for_each
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/iter/traits/iterator.rs:736:9
   9: <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/alloc/src/vec/spec_extend.rs:40:17
  10: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/alloc/src/vec/spec_from_iter_nested.rs:56:9
  11: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/alloc/src/vec/spec_from_iter.rs:33:9
  12: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/alloc/src/vec/mod.rs:2449:9
  13: core::iter::traits::iterator::Iterator::collect
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/iter/traits/iterator.rs:1748:9
  14: move_model::ty::Type::replace::{{closure}}
             at ./language/move-model/src/ty.rs:266:44
  15: move_model::ty::Type::replace
             at ./language/move-model/src/ty.rs:293:70
  16: move_model::ty::Type::instantiate
             at ./language/move-model/src/ty.rs:233:13
  17: move_model::ty::Type::instantiate_vec::{{closure}}
             at ./language/move-model/src/ty.rs:242:38
  18: core::iter::adapters::map::map_try_fold::{{closure}}
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/iter/adapters/map.rs:89:28
  19: core::iter::traits::iterator::Iterator::try_fold
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/iter/traits/iterator.rs:1972:21
  20: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/iter/adapters/map.rs:115:9
  21: <I as alloc::vec::source_iter_marker::SpecInPlaceCollect<T,I>>::collect_in_place
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/alloc/src/vec/source_iter_marker.rs:117:13
  22: alloc::vec::source_iter_marker::<impl alloc::vec::spec_from_iter::SpecFromIter<T,I> for alloc::vec::Vec<T>>::from_iter
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/alloc/src/vec/source_iter_marker.rs:55:19
  23: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/alloc/src/vec/mod.rs:2449:9
  24: core::iter::traits::iterator::Iterator::collect
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/iter/traits/iterator.rs:1748:9
  25: move_model::ty::Type::instantiate_vec
             at ./language/move-model/src/ty.rs:242:13
  26: move_model::ast::ExpData::instantiate_node::{{closure}}
             at ./language/move-model/src/ast.rs:707:55
  27: core::option::Option<T>::map
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/option.rs:489:29
  28: move_model::ast::ExpData::instantiate_node
             at ./language/move-model/src/ast.rs:707:29
  29: <move_model::ast::ExpRewriter as move_model::exp_rewriter::ExpRewriterFunctions>::rewrite_node_id
             at ./language/move-model/src/ast.rs:822:9
  30: move_model::exp_rewriter::ExpRewriterFunctions::internal_rewrite_id
             at ./language/move-model/src/exp_rewriter.rs:324:31
  31: move_model::exp_rewriter::ExpRewriterFunctions::rewrite_exp_descent
             at ./language/move-model/src/exp_rewriter.rs:194:44
  32: move_model::ast::ExpData::rewrite_node_id
             at ./language/move-model/src/ast.rs:673:9
  33: bytecode::spec_instrumentation::Instrumenter::instantiate_exp
             at ./language/move-prover/bytecode/src/spec_instrumentation.rs:1078:9
  34: bytecode::spec_instrumentation::Instrumenter::emit_lets
             at ./language/move-prover/bytecode/src/spec_instrumentation.rs:847:23
  35: bytecode::spec_instrumentation::Instrumenter::instrument_call
             at ./language/move-prover/bytecode/src/spec_instrumentation.rs:546:9
  36: bytecode::spec_instrumentation::Instrumenter::instrument_bytecode
             at ./language/move-prover/bytecode/src/spec_instrumentation.rs:492:17
  37: bytecode::spec_instrumentation::Instrumenter::instrument
             at ./language/move-prover/bytecode/src/spec_instrumentation.rs:417:13
  38: bytecode::spec_instrumentation::Instrumenter::run
             at ./language/move-prover/bytecode/src/spec_instrumentation.rs:267:9
  39: <bytecode::spec_instrumentation::SpecInstrumentationProcessor as bytecode::function_target_pipeline::FunctionTargetProcessor>::process
             at ./language/move-prover/bytecode/src/spec_instrumentation.rs:122:33
  40: bytecode::function_target_pipeline::FunctionTargetProcessor::process_and_maybe_remove
             at ./language/move-prover/bytecode/src/function_target_pipeline.rs:96:14
  41: bytecode::function_target_pipeline::FunctionTargetsHolder::process
             at ./language/move-prover/bytecode/src/function_target_pipeline.rs:263:43
  42: bytecode::function_target_pipeline::FunctionTargetPipeline::run_with_hook
             at ./language/move-prover/bytecode/src/function_target_pipeline.rs:370:21
  43: bytecode::function_target_pipeline::FunctionTargetPipeline::run
             at ./language/move-prover/bytecode/src/function_target_pipeline.rs:380:9
  44: move_prover::create_and_process_bytecode
             at ./language/move-prover/src/lib.rs:246:9
  45: move_prover::run_move_prover_with_model
             at ./language/move-prover/src/lib.rs:114:19
  46: move_prover::run_move_prover
             at ./language/move-prover/src/lib.rs:58:5
  47: move_prover::run
             at ./language/move-prover/src/main.rs:33:5
  48: move_prover::main
             at ./language/move-prover/src/main.rs:12:21
  49: core::ops::function::FnOnce::call_once
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/ops/function.rs:227:5
```

**Comment by mengxu-fb** [comment]
More bug fixes to do!

**Comment by sblackshear** [comment]
Really appreciate you looking into this!
