### ISSUE TITLE
[Bug] move panic when running a script that packs a struct from a different module

### ISSUE THREAD

**Issue by lxfind** [diem/diem#9907]
# 🐛 Bug

Following the tutorial in https://github.com/diem/diem/blob/main/language/documentation/book/src/creating-coins.md, where we are trying to pack a struct in a script. The struct is defined in a different module and hence we are expecting to see a type error.
However the TypeSafety::Visibility diagnostics is in fact a "NonblockingError", which means trying to pack a struct defined from a different module will not result in a blocking error. This eventually causes move bytecode translation to panic (since bytecode gen assumes same module when packing).

## To reproduce

Follow the tutorial, define a module:
```rust
address 0x2 {
    module Coin {

        struct Coin {
            value: u64,
        }

    }
}
```
Then define a script:
```rust
script {

    use 0x2::Coin::Coin;

    fun main() {
        let _coin = Coin { value: 100 };
    }
}
```

Run the script.

**Stack trace/error message**
```
 % RUST_BACKTRACE=1 move sandbox run scripts/test-coin.move
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', language/move-lang/src/to_bytecode/translate.rs:1003:77
stack backtrace:
   0: rust_begin_unwind
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:517:5
   1: core::panicking::panic_fmt
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/panicking.rs:101:14
   2: core::panicking::panic
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/panicking.rs:50:5
   3: move_lang::to_bytecode::translate::exp_
   4: move_lang::to_bytecode::translate::function
   5: move_lang::to_bytecode::translate::program
   6: move_lang::command_line::compiler::run
   7: move_lang::command_line::compiler::run
   8: move_lang::command_line::compiler::run
   9: move_lang::command_line::compiler::run
  10: move_lang::command_line::compiler::run
  11: move_lang::command_line::compiler::run
  12: move_lang::command_line::compiler::SteppedCompiler<_>::run
  13: move_lang::command_line::compiler::Compiler::run
  14: move_lang::command_line::compiler::Compiler::build
  15: move_lang::command_line::compiler::Compiler::build_and_report
  16: move_package::compilation::compiled_package::CompiledPackage::build
  17: move_package::compilation::build_plan::BuildPlan::compile
  18: move_package::BuildConfig::compile_package
  19: move_cli::sandbox::utils::package_context::PackageContext::new
  20: move_cli::sandbox::cli::SandboxCommand::handle_command
  21: move_cli::run_cli
  22: move_cli::move_cli
  23: move::main```

## Expected Behavior

Proper error message like this:
```
All structs can only be constructed in the module in which they are declared
```

**Comment by modocache** [comment]
Nice report, thanks @lxfind! I brought this up in #9550 as well. One immediate cause is that the restricted visibility error that should cause the error message you're expecting is currently being treated as a "non-blocking" error. This allows execution of the compiler to continue to bytecode generation and, without this struct type resolved, it panics. Another issue is that diagnostics are printed at the end of execution, so if the compiler panics, diagnostics are not printed -- that's why you see only the stack trace here, and no error messages.

One fix could be, as in #9550, to revert this error back to a "blocking" error that would prevent the compiler from continuing its execution and panicking. IMHO another improvement would be to install something like a signal handler that prints any queued up diagnostics if the compiler crashes.

(And, FWIW, part of my plan for next year is to add automated tests for these Move book examples, so we can make sure they continue working as documented.)
