### ISSUE TITLE
[Bug] compiler panicked at 'ICE type checking failed'

### ISSUE THREAD

**Issue by bob-wilson** [diem/diem#9987]
# 🐛 Bug

I'm getting a crash in the Move compiler, with 'ICE type checking failed' at language/move-lang/src/hlir/translate.rs:970:26

## To reproduce

**Code snippet to reproduce**
Apply the following patch to language/documentation/tutorial/step_7/BasicCoin/sources/BasicCoin.move:
```
@@ -42,7 +42,9 @@ module NamedAddr::BasicCoin {
     /// Transfers `amount` of tokens from `from` to `to`. This method requires a witness with `CoinType` so that the
     /// module that owns `CoinType` can  decide the transferring policy.
     public fun transfer<CoinType: drop>(from: &signer, to: address, amount: u64, _witness: CoinType) acquires Balance {
-        let check = withdraw<CoinType>(Signer::address_of(from), amount);
+        let addr_from = Signer::address_of(from);
+        assert!(addr_from != to);
+        let check = withdraw<CoinType>(addr_from, amount);
         deposit<CoinType>(to, check);
     }
```
Then run `move package build` for the step_7/BasicCoin package.

**Stack trace/error message**
```
$ move package build
CACHED MoveStdlib
BUILDING BasicCoin
thread 'main' panicked at 'ICE type checking failed', language/move-lang/src/hlir/translate.rs:970:26
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

## Expected Behavior

My code may be wrong here, but if so, the compiler should give me a nice message, not a panic.

## System information

I built the tools following the setup instructions in the Move tutorial. I'm at git commit 9f2aa64e4c

**Comment by bob-wilson** [comment]
I get the same error if I simplify the patch and just insert the one assertion line in the transfer function:
`assert!(Signer::address_of(from) != to);`

**Comment by bob-wilson** [comment]
Oh! I'm missing the 2nd argument to the assertion. Still, the compiler should not crash on this!

**Comment by tnowacki** [comment]
Do you have a fresh install of the move-cli. I could not reproduce the bug?

**Comment by bob-wilson** [comment]
> Do you have a fresh install of the move-cli. I could not reproduce the bug?

Todd confirmed off-line that he can reproduce the bug now
